### ISSUE TITLE
does not run locally on podman

### ISSUE THREAD

**Issue by rbaumgar** [RedHat-Middleware-Workshops/rhpam-rhdm-workshop-v1m1-guides#4]
on RHEL 8.3

```
$ podman run -it --rm -p 8080:8080 -v $(pwd)/:/app-data -e CONTENT_URL_PREFIX="file:///app-data" -e WORKSHOPS_URLS="file:///app-data/_rhpam-rhdm-workshop-module1.yml" -e LOG_TO_STDOUT=true quay.io/osevg/workshopper
WARN[0000] Found deprecated file /home/rbaumgar/.config/containers/libpod.conf, please remove. Use /home/rbaumgar/.config/containers/containers.conf to override defaults. 
WARN[0000] Found deprecated file /home/rbaumgar/.config/containers/libpod.conf, please remove. Use /home/rbaumgar/.config/containers/containers.conf to override defaults. 
WARN[0000] Found deprecated file /home/rbaumgar/.config/containers/libpod.conf, please remove. Use /home/rbaumgar/.config/containers/containers.conf to override defaults. 
WARN[0000] Found deprecated file /home/rbaumgar/.config/containers/libpod.conf, please remove. Use /home/rbaumgar/.config/containers/containers.conf to override defaults. 
Trying to pull quay.io/osevg/workshopper:latest...
Getting image source signatures
Copying blob a3ed95caeb02 done  
Copying blob a3ed95caeb02 done  
Copying blob a3ed95caeb02 done  
Copying blob a3ed95caeb02 done  
Copying blob a02a4930cb5d done  
Copying blob 94b5f27d801e done  
Copying blob 0826c103698c done  
Copying blob 90b5bd1fb806 done  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob 7483b34a94f0 done  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob 77d3b0f9fde0 done  
Copying blob fdf66a71aa9a done  
Copying blob 0f4176a49cb9 done  
Copying blob 663def05ea5c done  
Copying blob c9d7d3cc0226 done  
Copying blob 32926c2219ca done  
Copying blob 581bc8741e82 done  
Copying blob 46f738a27120 done  
Copying blob 5a9881a82cc3 done  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob a3ed95caeb02 skipped: already exists  
Writing manifest to image destination
Storing signatures
bundler: failed to load command: rackup (/workshopper/vendor/bundle/ruby/2.5.0/bin/rackup)
Errno::EACCES: Permission denied @ rb_sysopen - /app-data/_rhpam-rhdm-workshop-module1.yml
  /workshopper/lib/workshopper/loader/file.rb:9:in `initialize'
  /workshopper/lib/workshopper/loader/file.rb:9:in `open'
  /workshopper/lib/workshopper/loader/file.rb:9:in `get'
  /workshopper/lib/workshopper/loader.rb:17:in `get'
  /workshopper/lib/workshopper/workshop.rb:13:in `initialize'
  /workshopper/lib/workshopper/cache.rb:12:in `new'
  /workshopper/lib/workshopper/cache.rb:12:in `add'
  /workshopper/config/initializers/workshopper.rb:8:in `block in <top (required)>'
  /workshopper/config/initializers/workshopper.rb:7:in `each'
  /workshopper/config/initializers/workshopper.rb:7:in `<top (required)>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:415:in `call'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /opt/essentials/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
  /workshopper/config/environment.rb:5:in `<top (required)>'
  /workshopper/config.ru:3:in `require_relative'
  /workshopper/config.ru:3:in `block in <main>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  /workshopper/config.ru:in `new'
  /workshopper/config.ru:in `<main>'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:283:in `start'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
  /workshopper/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
  /workshopper/vendor/bundle/ruby/2.5.0/bin/rackup:23:in `load'
  /workshopper/vendor/bundle/ruby/2.5.0/bin/rackup:23:in `<top (required)>'
```

**Comment by rbaumgar** [comment]
you do not need to git clone. Just run
```
$ podman run -p 9002:8080 -it --rm --name=lab-guide -e CONTENT_URL_PREFIX="https://raw.githubusercontent.com/RedHat-Middleware-Workshops/rhpam-rhdm-workshop-v1m1-guides/master" -e WORKSHOPS_URLS="https://raw.githubusercontent.com/RedHat-Middleware-Workshops/rhpam-rhdm-workshop-v1m1-guides/master/_rhpam-rhdm-workshop-module1.yml" -e LOG_TO_STDOUT=true quay.io/osevg/workshopper
```
